version: '3'

services:
  db:
    image: mysql:5.7
    container_name: web-db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: web
      MYSQL_USER: web
      MYSQL_PASSWORD: webdesigncourse
    ports:
      - "3306:3306"
  web:
    image: kosar/nginx-php:7.4
    container_name: web
    depends_on:
      - db
    volumes:
      - ./:/var/www/html
    ports:
      - "8080:80"

